#!/bin/bash
#BSUB -J all_bl_bruteforce_fh_and_ds_10000_2018pegasus
#BSUB -o all_bl_bruteforce_fh_and_ds_10000_2018pegasus.out
#BSUB -e all_bl_bruteforce_fh_and_ds_10000_2018pegasus.err
#BSUB -P premaratne
#BSUB -q bigmem 
#BSUB -n 1
#BSUB -W 119:00
#BSUB -B
#BSUB -N
#BSUB -u lalintha@umiami.edu
#
# Run serial executable on 1 core of one node
./all_bl_bruteforce
